export const API_ENDPOINTS = {
  authLogin: '/api/auth/login',
  authRegister: '/api/auth/register',
  authRefresh: '/api/auth/refresh',
  authLogout: '/api/auth/logout',
  me: '/api/me',
  mePassword: '/api/me/password',
  nodes: '/api/nodes',
  node: (id: string) => `/api/nodes/${id}`,
  nodeRestore: (id: string) => `/api/nodes/${id}/restore`,
  nodePermissions: (id: string) => `/api/nodes/${id}/permissions`,
  adminUsers: '/api/admin/users',
  adminUserRole: (id: string) => `/api/admin/users/${id}/role`,
  adminUserForceLogout: (id: string) => `/api/admin/users/${id}/force-logout`,
  adminGroups: '/api/admin/groups',
  adminGroup: (id: string) => `/api/admin/groups/${id}`,
  adminGroupMembers: (id: string) => `/api/admin/groups/${id}/members`,
  adminGroupMember: (groupId: string, uid: string) =>
    `/api/admin/groups/${groupId}/members/${uid}`,
} as const
